### ISSUE TITLE
Forklift emits Last Insert Date as an event

### ISSUE THREAD

**Issue by jakeprem** [smartcitiesdata/smartcitiesdata#206]
Currently Forklift writes the Last Insert Date directly to Redis, then Discovery API retrieves that value directly from Redis when displaying a dataset to a user.

Forklift should emit an event with the Last Insert Date, including the dataset ID, the last insert date, and any other relevant data.

Discovery API should consume the Last Insert Date event and update its view state accordingly.

AC:
  * [x] Forklift emits a Last Insert Date event
  * [x] Forklift does not write Last Insert Date directly to Redis
  * [x] Discovery API consumes Last Insert Date event and updates its view state
  * [x] Discovery API displays the Last insert date based on its View state, not based a value Forklift inserted into Redis

TN:
  * It might be possible that this information is already captured by events currently being written to the event stream. If that is the case then Discovery API should consume that instead and Forklift should cease writing to Redis.
- This includes a migration

**Comment by jeffgrunewald** [comment]
Is this related to an existing "event" that is already happening and being emitted such as "ingest:end"? If so, can this value just be included as an element of that value that is stored in forklift view state as part of the event?

**Comment by jakeprem** [comment]
That's what the tech note is about

**Comment by bbrewer-papa-x** [comment]
The existing events are close, but not entirely ideal. It looks like our best bet in the arena would be data:extract:end, which, unfortunately does not necessarily indicate that data has been successfully written to Presto.

We're going to put in an event send where it the redis write would have been in the Forklift pipeline writer implementation.

Otherwise, we plan on merging the timestamp into the Dataset Model on event receive for Discovery API.
