### ISSUE TITLE
Mitigate high risk vulnerability in andi dependency

### ISSUE THREAD

**Issue by jeffgrunewald** [smartcitiesdata/smartcitiesdata#270]
**Describe the bug**
Andi static assets includes the npm library js-yaml with a high severity security vulnerability in the current version.

**To Reproduce**
Go to github repo and click into the banner to see the details of the automatically detected vulnerable package.

This is not a direct dependency but a transitive one included in the package.lock file.

**Comment by jakeprem** [comment]
Looks like this can be fixed by updating https://www.npmjs.com/package/optimize-css-assets-webpack-plugin. It's a major version bump, so I'm not sure what risks or what issues it might cause, but it's also only used to process CSS as part of our webpack, so it might not require any additional changes on our part.

Or maybe there's a change in the configuration format?

```
diff --git a/apps/andi/assets/package.json b/apps/andi/assets/package.json
index a38f847..857f404 100644
--- a/apps/andi/assets/package.json
+++ b/apps/andi/assets/package.json
@@ -20,7 +20,7 @@
     "mini-css-extract-plugin": "^0.4.0",
     "node-sass": "^4.13.0",
     "normalize.css": "^8.0.1",
-    "optimize-css-assets-webpack-plugin": "^4.0.0",
+    "optimize-css-assets-webpack-plugin": "^5.0.3",
     "sass-loader": "^8.0.0",
     "uglifyjs-webpack-plugin": "^1.2.4",
     "webpack": "4.41.2",
```
