### ISSUE TITLE
CD for Estuary

### ISSUE THREAD

**Issue by kcarra** [smartcitiesdata/smartcitiesdata#340]
Summary: As Dave the developer I would like to have a CD pipeline that deploys the latest code in master to the proper environment so that I don't need to do manual deployments.

AC:
- [ ] Code in master/in a release is deployed to proper environment
- [ ] Test that log level is configurable based on estuary config file not umbrella config file.

Tech note:
- Deploying to prod will still be a manual process

**Comment by rajones-hntb** [comment]
Is our deployment code going to be opened sourced or will we keep that private somewhere?

**Comment by kcarra** [comment]
Good point! Estuary-deploy will be in SmartColumbusOS because that is Columbus implementation specific.

**Comment by dunson062786** [comment]
In [read events from event stream](https://github.com/smartcitiesdata/smartcitiesdata/issues/342) we couldn't test if our logger level was different in test vs dev since it was in an umbrella app. So when we deploy we should check the logger level in docker for each environment to see if it is picking up the umbrella logger or estuary logger.
