### ISSUE TITLE
Compact Estuary Tables

### ISSUE THREAD

**Issue by dunson062786** [smartcitiesdata/smartcitiesdata#392]
#### User Story
As a developer
I want to estuary inserts compacted daily
So that data reads and write operations will be faster

#### Acceptance Criteria: 
- [ ] All rows get consolidated daily

#### Tech Notes: 
- Quantum job to consolidate all rows daily

#### Amigos: 
@jmorris-pillar @ManApart

**Comment by ManApart** [comment]
Questions I have on this card as we've been working through it
 - Do we need to collect metrics for compaction?
  - Pretty sure we don't since we're not recording write times etc
- Do we need a separate compaction gen server?
  - Forklift has one, but I think that's only necessary since its writers are one per dataset
  - We restart pipline when it goes down, but I think we can get away with killing and then restarting the reader without it taking pipeline down. This needs verified.
- Do we need the extra args forklift has? Forklift is passing a lot more to reader/writer than we are. Confirm we're not missing something
- If compaction fails, should the app crash or keep going? 
  - Keep going
    - Consistent with forklift
    - Don't build up a backlog of unread events
  - Crash
    - More noticeable / easier to realize there is a problem
    - Prevent getting into state where table too large to compact
