### ISSUE TITLE
[documentation] [help wanted] [question] How to run locally?

### ISSUE THREAD

**Issue by tommy-elliott-awh** [smartcitiesdata/smartcitiesdata#598]
I've created a fork of this repository (https://github.com/AWHServiceAccount/smartcitiesdata) and I've been trying for a few days to understand this project's parts and to get it to a point where I can run the system locally, but I'm a bit stuck in terms of understanding how to use minikube/helm/kubectl or whatever would be needed in order to get to a usable version of the system and its many components running on my machine using docker images and containers.

The main difficulty is that the main readme documentation for the repository states that to run the system locally, you just need to run `docker pull && docker-compose up -d`, but neither of those commands will execute as described.

`docker pull` needs an argument (the name of the image to pull, with optional tag); and in searching for docker images with smartcitiesdata in their name using `docker search smartcitiesdata` I get results, but trying to pull any of those using `docker pull smartcitiesdata/andi` for example doesn't work because I get
`Using default tag: latest
Error response from daemon: manifest for smartcitiesdata/andi:latest not found: manifest unknown: manifest unknown`
for all of those search results except for smartcitiesdata/data-generator, which pulls successfully.

`docker-compose up -d` needs there to be a docker-compose.yaml file in the root repository directory, which doesn't exist, since a commit from 10/8/19 (https://github.com/smartcitiesdata/smartcitiesdata/commit/65f1a15b) that removed it (commit message: "Remove docker-compose support").

What I'd like to be able to do is to get the system running locally from docker images built from my local repository code so that I can eventually modify the code and have the modifications able to be reflected in what I run locally.  It appears that the local development instructions need to be updated from what exists in the main readme to be correct for how local development actually should be initiated.

I'm developing on a Windows machine, so I set up my environment using Windows Subsystem for Linux (WSL) and I've installed and got to a workable setup all listed needed tools described in the wiki documentation, using that documentation along with finding additional guides online as they relate to using WSL with some of the tools.  I also had to make a few code modifications regarding how git handles CRLF newlines vs LF newlines in *.sh files so they could be executed.

By looking through the scripts folder's contents and interpreting those along with the .travis.yml file in the repository root folder, I was able to execute what seem to be most of the steps involved in building and running tests on the components of the system.

I'm still trying to work out the steps needed for building each docker image locally (seems to be `scripts/build.sh <component-name> development`, but I'm not entirely sure).  Ultimately, even once I have all the docker images locally, how should I go about running all those in docker containers locally via something (maybe minikube with kubectl?) that would allow for the necessary interactions between each of the components such that it would be functional as a system?

Another uncertainty I have is whether or not the publish.sh script (if I were to create my own Docker Hub username/password and configure those login credentials to be usable by that script) would overwrite the public searchable docker images for the main smartcitiesdata/smartcitiesdata repository.  It also seems that some sort of Travis account connection would need to be made to make the .travis.yml configured operations execute on pull requests or pushes to master - what would be needed for those steps?  Recall that I'm working in a fork of this repository, so I don't want to overwrite or cause issues with any of the base repository's published images.

The steps that are the answers to these questions, and if necessary, the steps leading up to this point seem like they would be of benefit to others if they were written into the system setup wiki pages and the main readme file in the repository root.

**Comment by jeffgrunewald** [comment]
hey @tommy-elliott-awh thanks for the issue and bringing the outdated instructions to our attention.

I have a PR out to the team to update the documentation and steer folks away from docker-compose since, as you've mentioned, the compose file was removed a while ago. The new instructions will direct you toward the `smartcitiesdata/charts` repo in this org to use the helm charts to stand up the platform in a kubernetes cluster, such as minikube or built into docker desktop.

For all of the project docker images, you can find them on the `smartcitiesdata` dockerhub account under semver release tags or a single floating `development` tag. If you'd like to build your own, you'll need to `docker tag <name>` to include your own username. Dockerhub requires push permissions so you won't be able to overwrite any of the project images. If you'd like to use Travis for your own CI, you'll need to authorize it to access your fork of the project and update your copy of `.travis.yml` accordingly; Travis requires admin access to a repo so once again, there's no risk of your own fork interfering with the upstream project but leaving a copy of Travis file unmodified will cause your own builds to break.

In order to deploy the project with helm to k8s, you can update the `values.yaml` file to point each app's `image`  and `tag` fields to the dockerhub image and tag you want or set them at the command line with the `--set` flag when you deploy. To use reaper as an example you'd run the helm command `helm upgrade --install [other stuff here] --set reaper.image.repository=mydockeraccount/reaper,reaper.image.tag=0.1.whatever`

If you're more comfortable with docker-compose, or you just don't want to fight with kubernetes and helm, you can reconstruct the docker-compose file or use the one from this repo's history as a starting point. In compose, once you've selected what version of each image to run, you can pull them all with the `docker-compose pull` command which is probably what the original readme instructions were intending to convey.

Hope that helps get you going.

**Comment by tommy-elliott-awh** [comment]
Hi @jeffgrunewald that has gotten me farther along, thank you.

Now I'm stuck again regarding needing configuration info for databases and admin users and hosted storage that I just don't have right now and that I don't know how to set up.  I also don't know if empty databases are sufficient or not, or whether there are ways to have those needs met besides creating cost-incurring resources in a cloud service like AWS or Azure.

I'm to a point where I have my own Docker Hub images (under awhdockerhub) built and tagged for both development and for the latest version number for each for the 9 main components from the smartcitiesdata repo (andi; discovery_api; discovery_streams; estuary; flair; forklift; odo; reaper; valkyrie).  I also have the repo code for the forked charts repo updated to point to the new Docker Hub account's images and each of the individual 9 helm charts packaged with only default config info.

However, the main issue I have right now is configuring info (when packaging the helm charts both individually and for the whole system) for connecting to postgres databases and redis databases and for S3 bucket names and access keys and admin usernames and passwords.  It appears like I would need to have all of these (see below excerpt from the charts/platform/README.md file visible at https://github.com/smartcitiesdata/charts/tree/master/platform ) to have appropriate values, and I have none of them currently, nor the knowledge to set them up; not to mention whether they would need any initial setup like table schema, besides just being hosted and accessible.  There is one example usage of this `helm upgrade --install platform scdp/platform ...` command in the same readme, but without any real usernames/passwords.
```
# Required Parameters
kubernetes-data-platform.global.objectStore.bucketName=<S3 BUCKET NAME HERE>
kubernetes-data-platform.global.objectStore.accessKey=<S3 BUCKET ACCESS KEY HERE>
kubernetes-data-platform.global.objectStore.accessSecret=<S3 BUCKET SECRET HERE>
kubernetes-data-platform.postgres.service.externalAddress=<POSTGRES DB LOCATION HERE >
kubernetes-data-platform.postgres.db.user=<POSTGRES DB USER HERE>
kubernetes-data-platform.postgres.enable=<SPIN UP POSTGRES POD?>
kubernetes-data-platform.postgres.db.password=<POSTGRES DB PASSWORD HERE>
kubernetes-data-platform.kdp.s3.hostedFileBucket=<BUCKET NAME HERE>
discovery-api.postgres.host=<HOST HERE>
discovery-api.s3.hostedFileBucket=<HOST HERE>
openldap.adminPassword=admin
discovery-api.postgres.dbname=metastore
discovery-api.postgres.user=<DB USERNAME>
discovery-api.postgres.password=<DB PASSWORD>
discovery-api.redis.host=<REDIS_HOST>
discovery-api.redis.password=<REDIS_PASSWORD>
reaper.redis.host=<REDIS_HOST>
reaper.redis.password=<REDIS_PASSWORD>
valkyrie.redis.host=<REDIS_HOST>
valkyrie.redis.password=<REDIS_PASSWORD>
forklift.redis.host=<REDIS_HOST>
forklift.redis.password=<REDIS_PASSWORD>
andi.redis.host=<REDIS_HOST>
andi.redis.password=<REDIS_PASSWORD>
forklift.postgres.host=<DB SERVER NAME same as above>
```

Must I create each of these database servers and instances and object stores and access keys and user credentials for database access and such in a cloud-hosted environment like AWS or Azure?  If not, what other options do I have?

Also, for any of these, is any additional table schema or setup needed besides having read and write access via these configured values?

**Comment by jeffgrunewald** [comment]
If you're deploying locally to a development k8s cluster than you need to explicitly deploy the "kubernetes-data-platform" and "redis" components. If you're using the `platform` chart within the smartcitiesdata/charts repo to do your full-stack deployment to a local cluster then this is disabled by default and you'll need to toggle them on in the values file or by passing the necessary `--set <component>.enabled=true` flag when you run your deploy command.

That will come with a postgres database for Presto's Hive Metastore component and you can probably use that safely for the Discovery-Api postgres requirement if you're just working in a development environment but I would encourage you to add the standard community Postgres helm chart to your `requirements.yaml` file and make a dedicated postgres for the app so you don't have to juggle permissions on a single postgres container between discovery and presto's requirements. The team actively working on the project at the moment (of which I'm no longer a member) has not been doing much full-stack local development so that is why the documentation and the helm charts to support it have not been kept up to date.

The charts assumes you are running in a cloud environment first and in that case, it's up to you to use whatever tooling your team prefers to manage your infrastructure and then collect things like database names, passwords, and bucket names and pass them to the chart to pass to the applications running in kubernetes. When you're running locally and turning on those components in kubernetes they should be passed to your applications automatically. Give that a try and see if there are any components still not wired together.

**Comment by tommy-elliott-awh** [comment]
Thank you again.  We're getting closer now.

Getting into the details of each of the required resources now, it would be great if I could meet with someone this week, any available expert on the setup, for about 4h to 6h (though the more time the better) to talk me through how to set up for first-time use an instance of the full platform and to run it in containers locally, especially assisting in setting up the necessary resources and credentials for various file and data storage, and in how to set up data curation organizations, users, and dataset definitions.

These are the primary remaining questions to discuss (some of which have been partially addressed, but still have unknowns):

1. How can one run the platform chart to run the full system, with file and data storage being hosted in containers locally?
2. How can one run the platform chart to run the full system, with file and data storage being hosted in Google Cloud (or Azure or AWS)?
3. How does user security and data access scope for each user work in the andi website?
4. How can one add data curation organizations, users, and dataset definitions once the system is running?
5. How can one set up the discovery_ui website to be navigable by a user?
6. How does user security and data access scope for each user work in the discovery_ui website?
7. Is an Auth0 tenant needed to be configured per environment for either andi or discovery_ui or both?

**Comment by JarredOlson** [comment]
@tommy-elliott-awh I'm currently working with the Smart Columbus Team and we would be able to setup a 30-60 minute meeting with you to help understand some of your pain points and see if we can further help out. If you can work through Jordan we should be able to get something scheduled.
