### ISSUE TITLE
SPIKE - Kibana Weighting and Synonyms

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#641]
Questions:

1. Can we modify the Weighting via the Kibana Dashboard
2. Can we modify the Synonyms via the Kibana Dashboard
3. Validate the Analytics we can tack

**Comment by bbrewer-forge** [comment]
RE: Metrics
APM is not available trivially
- this would provide search metrics like what was searched and how long the searches took
- this requires a server (can be set up as an appliance in AWS) and agents (none built for Elixir though)
- additionally, the dashboard for this would not be in Kibana

**Comment by bbrewer-forge** [comment]
RE: Weighting/Boosting
https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-boost.html
^ ES says don't do it at index time

Otherwise, it does work, and if we want to do it, we need to consider how that would play with our current setup of re-building the index from configuration every time that API restarts

**Comment by bbrewer-forge** [comment]
RE: Synonyms
These require closing and re-opening the index, which AWS ES doesn't support :(
They do work though

**Comment by bbrewer-forge** [comment]
RE: standing up our cluster:
- there are 2 options that are immediate
- official helm chart
  - config based (tweak the values file)
- official k8s cloud operator
  - use CRDs to build ElasticSearch, APM, Kibana, etc.

**Comment by bbrewer-forge** [comment]
Details on running a self-hosted Elasticsearch cluster + Kibana can be found at https://github.com/SmartColumbusOS/spike-on-prem-elasticsearch

Overall findings:
- Self-hosted gives us the `Basic` license which allows us to use Canvas, APM, App Search and a TON of other features
- However, query tracking is something you always have to figure out on your own, unless you had the foresight to make your app use App Search directly, instead of ES
- The amount of effort to setup Packetbeats, the drawback of having to have ES be non-TLS, and the issues I've had in the past maintaining log pipelines like this in the past make it seem like a little too much work.
- Otherwise, query tracking findings generally point towards either a proxy, or implementing metrics on your own.

At this point, if we can live without Canvas, and can deal with how difficult it is to do relevance tweaks, then I would strongly recommend just taking a bit of time for us to add query tracking in Discovery API on our own. It could basically just ship the details (query, facets, result size, etc.) to ES and then the metrics could be visualized there to get an idea of what's going on.
