### ISSUE TITLE
SPIKE: Handle load of CVE Data

### ISSUE THREAD

**Issue by JarredOlson** [smartcitiesdata/smartcitiesdata#915]
The Columbus CVE implementation will require us to collect data from ~90 RSUs (Road Side Units).  Currently we see a large amount of data from only 2 of those RSUs.

Questions:
- [ ] How many RSUs can the push gateway handle?
- [ ] How many RSUs can valkyrie handle?
- [ ] How many RSUs can forklift handle?
- [ ] Are these applications limited by CPU/Memory/Network?

By "Handle" I mean able to keep up with the load.
In staging please start doubling the RSUs we are listening to and evaluating each app after each doubling.  I can provide some different RSUs (all 90 are not working), but deploying a duplicate docker image listening to the same RSU should be sufficient.

**Comment by bbrewer-forge** [comment]
Good to know limits per service, but also messages per second/minute etc. per RSU

**Comment by JarredOlson** [comment]
morse_sunbury_rsu
morse_stygler_rsu
morse_lbrands_rsu
morse_appian_rsu
morse_I270sb_rsu
morse_eastonloop_rsu
morse_stelzer_rsu
morse_morsecrossing_rsu
morse_chesford_rsu
morse_cleveland_rsu
morse_malin_rsu
morse_walford_rsu
morse_northlandridge_rsu
morse_karl_rsu
morse_maize_rsu
morse_si71ramp_rsu
cleveland_cooke_rsu
morse_sandylane_rsu
cleveland_ferris_rsu
cleveland_elmore_rsu
cleveland_innis_rsu
cleveland_huy_rsu
cleveland_oaklandpark_rsu
cleveland_weber_rsu
cleveland_westerville_rsu
cleveland_genessee_rsu
cleveland_myrtle_rsu
cleveland_hudson_rsu
cleveland_duxberry_rsu
cleveland_24th_rsu
cleveland_20th_rsu
cleveland_windsor_rsu
cleveland_11th_rsu
cleveland_5th_rsu
cleveland_2nd_rsu
high_kelso_rsu
high_weber_rsu
high_pacemount_rsu
high_como_rsu
high_northbroadway_rsu
high_oaklandpark_rsu
high_torrence_rsu
high_henderson_rsu
high_dominion_rsu
high_weisheimer_rsu

**Comment by bbrewer-forge** [comment]
First test, just a simple increase of the number of RSUs we're watching. In this case, just doubling the number from 3 total to 6 total, then increasing linearly. In this case marysville sends considerably more data than the columbus ones.

6 seems to handle pretty well though forklift gets some understandable backlog due to its wait setup. Will put some numbers here shortly.

**Comment by bbrewer-forge** [comment]
Prometheus queries for data (filtered for datasets in question)
Lag:
```
sum(kafka_consumergroup_lag{kubernetes_namespace="streaming-prime", topic=~".*([[dataset_id]]).*", consumergroup!~"console.*"} > 0) by (consumergroup, topic, dataset)
```

Produce rate:
```
sum(rate(kafka_topic_partition_current_offset{kubernetes_namespace="streaming-prime",  topic=~".*([[dataset_id]]).*"}[2m]) > 0) by (topic)
```

**Comment by bbrewer-forge** [comment]
From a test with real data in staging
- a single push gateway increased to 1 full CPU can handle at least 100 RSUs sending what is an average volume of data from Marysville - this ends up being ~7500 records per second or 75 records per RSU, which generally jibes with what we see on average from Marysville
- a single valkyrie without any tweaks can handle 100 RSUs sending what is an average volume of data from Marysville. note that it does have some trouble is the RSUs are split across 2 competing datasets. Having the two datasets split between valkyries does not appear to matter. More isolation is advised and I'm working on that in a "perf" sandbox env. It is likely a network contention problem, but we'll find out
- a single forklift without any tweaks can handle at least 72 RSUs sending what is an average volume of data form Marysville - this ends up being ~4000-500 records per second or 62 records per RSU, which generally jibes with what we see on average from Marysville

Further tests are going to be done in a perf environment with a uniform traffic generator, as the RSU traffic at the moment is very time of day dependent.

**Comment by bbrewer-forge** [comment]
Further isolation will be done to figure out where the bottleneck is for forklift. It is likely a CPU limitation, but also could be network or kafka tuning related (assume we're hitting the max data threshold rather than the max time threshold though, then it's largely a matter of how quickly we can write to both kafka and S3 - which "should" be a CPU/IO problem, but we'll see

Discover streams gives up somewhere between 36 and 72 RSUs as well, which requires further investigation

**Comment by bbrewer-forge** [comment]
Here is what I found after running 45 Columbus RSUs for 12 hours
- Max of 900 rps, so we could plan for that as the worst case of 900/45 rsus for 20 records per sec per RSU
- MAP records don't add much to that total, but in this case I'd bump it to a worst case of 30 records per sec per RUS
- MAP records also do NOT flow through valkyrie very well at all. We will need to play a card to investigate why it's so slow for them

**Comment by bbrewer-forge** [comment]
From this:
- RSUs handle-able by push gateway - at LEAST 200 columbus-like RSUs at 30rps (~7000 rps)
- RSUs handle-able by valkyrie - at LEAST 200 columbus-like RSUs at 30rps (~7000 rps)
- RSUs handle-able by forklift - at MOST 150 columbus-like RSUs at 30rps (~4500 rps)
- RSUs handle-able by discovery streams - at MOST ~60 columbus-like RSUs at 30rps (~2000 rps)

Otherwise
- valkyrie cannot handle MAP messages, can nail down why as part of this card or another
- discovery streams does not perform well at all, can nail down why as part of this card or another

**Comment by bbrewer-forge** [comment]
Only other unanswered question is how this deals with compaction

**Comment by bbrewer-forge** [comment]
Repo used to create more consistent levels of push data - https://github.com/SmartColumbusOS/push_gateway_generator

**Comment by bbrewer-forge** [comment]
Valky and MAP - https://app.zenhub.com/workspaces/smartcolumbusos-5d08f55f08ccbe75911ce796/issues/smartcitiesdata/smartcitiesdata/940
